### PR TITLE
Make Badge bold

### PR DESCRIPTION
**Pull request by elanoism**
According to discussion here - https://sumupteam.atlassian.net/browse/TOOL-428

**Changes**

- Adding `font-weight: bold` to `<Badge />`

### CODE REVIEW

**Comment by herberthenrique** [comment]
Hey man!
Can you make the font weight be a prop? 
 The same way we use in `Text` Component.

My designer was not expecting that `Badge` be bold 😅

**Comment by connor-baer** [comment]
@herberthenrique The badge label should always be bold for accessibility reasons. It was bold in Liam's original badge design and we had a discussion about this in regards to the transaction history (of course you couldn't know about this). 

Please ask your designer to use bold badge labels :)

**Comment by elanoism** [comment]
@herberthenrique, I don't mind adding it, but I guess the designers needs to be on the same page here.

I've started using `theme.fontWeight.bold` from theme and github automatically dismissed the reviews ... can you approve again, please?

**Comment by elanoism** [comment]
Thanks!

**Pull request merged**
