### PR TITLE
tech: Update React to latest v16.10

### PR DESCRIPTION
**Pull request by voronianski**
## Purpose

`@testing-library/react-hooks` was already bumped to v2.0.1 which requires `react-test-renderer` to be >= v16.9. However Circuit UI still has React v16.8 as dependency and it produces this kind of warning:

```
  console.error node_modules/@testing-library/react/dist/act-compat.js:88
    It looks like you're using a version of react-dom that supports the "act" function, but not an awaitable version of "act" which you will need. Please upgrade to at least react-dom@16.9.0 to remove this warning.
```

but more important that it prevents of using of `@testing-library/react-hooks`’s `waitForNextUpdate`  which relies on new async `act` method:

>Breaking Changes
Async act calls have increased the minimum react-test-renderer version to `16.9.0`
https://github.com/testing-library/react-hooks-testing-library/releases

Is there any specific reason why `react` wasn't upgraded to v16.9 yet?

## Approach and changes

- update `react`, `react-dom` and `react-test-renderer` to v16.10 (https://reactjs.org/versions/)

## Definition of done

* [x] Development completed
* [x] Reviewers assigned
* [x] Unit and integration tests
* [x] Meets minimum browser support
* [x] Meets accessibility requirements

### CODE REVIEW

**Comment by connor-baer** [comment]
I added `@testing-library/react-hooks` in error. We should remove it to get rid of the warning. 

We can't use hooks or a newer version of React yet since that would be a breaking change. I plan to do this in v2 and also make React a peer dependency (https://github.com/sumup/circuit-ui/issues/453).

**Comment by voronianski** [comment]
> I added `@testing-library/react-hooks` in error. We should remove it to get rid of the warning.
> 
> We can't use hooks or a newer version of React yet since that would be a breaking change. I plan to do this in v2 and also make React a peer dependency (#453).

Alright, I'm closing this one and will create new PR for fixing version of `@testing-library/react-hooks` to https://github.com/testing-library/react-hooks-testing-library/releases/tag/v1.1.0

**Comment by connor-baer** [comment]
I would remove `@testing-library/react-hooks` entirely. It's not used (yet).

**Comment by voronianski** [comment]
> I would remove `@testing-library/react-hooks` entirely. It's not used (yet).

I'm using it in Carousel PR as I have hooks to test there - https://github.com/sumup/circuit-ui/pull/482. I've changed version to `1.1.0` inside it.

**Pull request closed without merging**
